---
name: Text-ASCIITable-TW
version: v0.01
author:
  - 'Alec Chen <alec@cpan.org>'
abstract: plugin for TW support
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Encode: 2.26
  Moose: 0.55
  Test::More: 0
  version: 0.76
provides:
  Text::ASCIITable::TW:
    file: lib/Text/ASCIITable/TW.pm
    version: v0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
